kind: ConfigMap
apiVersion: v1
metadata:
  name: my-config
  namespace: app

data:

  SPRING_PROFILES_ACTIVE: "mysql"
  MYSQL_URL: "jdbc:mysql://db-svc:3306/devops"
  MYSQL_USER: "root"
  MYSQL_PASS: "admin"


